In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import sport_helpers
from sport_helpers import create_top_sport
from sport_helpers import create_enc

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn import tree

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
df = create_top_sport()

In [7]:
create_enc(df, ['nationality', 'sex', 'sport'])

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze,age,nationality_enc,sex_enc,sport_enc
0,736041664,A Jesus Garcia,ESP,male,1969-10-17,1.72,64.0,athletics,0,0,0,47,59,1,2
1,532037425,A Lam Shin,KOR,female,1986-09-23,1.68,56.0,fencing,0,0,0,30,101,0,8
2,435962603,Aaron Brown,CAN,male,1992-05-27,1.98,79.0,athletics,0,0,1,24,33,1,2
3,521041435,Aaron Cook,MDA,male,1991-01-02,1.83,80.0,taekwondo,0,0,0,25,117,1,21
4,33922579,Aaron Gate,NZL,male,1990-11-26,1.81,71.0,cycling,0,0,0,26,138,1,6
5,173071782,Aaron Royle,AUS,male,1990-01-26,1.80,67.0,triathlon,0,0,0,26,10,1,23
6,266237702,Aaron Russell,USA,male,1993-06-04,2.05,98.0,volleyball,0,0,1,23,191,1,24
7,382571888,Aaron Younger,AUS,male,1991-09-25,1.93,100.0,aquatics,0,0,0,25,10,1,0
8,87689776,Aauri Lorena Bokesa,ESP,female,1988-12-14,1.80,62.0,athletics,0,0,0,28,59,0,2
9,997877719,Ababel Yeshaneh,ETH,female,1991-07-22,1.65,54.0,athletics,0,0,0,25,61,0,2
10,343694681,Abadi Hadis,ETH,male,1997-11-06,1.70,63.0,athletics,0,0,0,19,61,1,2
11,591319906,Abbas Abubakar Abbas,BRN,male,1996-05-17,1.75,66.0,athletics,0,0,0,20,27,1,2
13,376068084,Abbey D'Agostino,USA,female,1992-05-25,1.61,49.0,athletics,0,0,0,24,191,0,2
14,162792594,Abbey Weitzeil,USA,female,1996-12-03,1.78,68.0,aquatics,1,1,0,20,191,0,0
15,521036704,Abbie Brown,GBR,female,1996-04-10,1.76,71.0,rugby sevens,0,0,0,20,67,0,17
16,149397772,Abbos Rakhmonov,UZB,male,1998-07-07,1.61,57.0,wrestling,0,0,0,18,192,1,26
17,256673338,Abbubaker Mobara,RSA,male,1994-02-18,1.75,64.0,football,0,0,0,22,155,1,9
18,337369662,Abby Erceg,NZL,female,1989-11-20,1.75,68.0,football,0,0,0,27,138,0,9
19,334169879,Abd Elhalim Mohamed Abou,EGY,male,1989-06-03,2.10,88.0,volleyball,0,0,0,27,56,1,24
20,215053268,Abdalaati Iguider,MAR,male,1987-03-25,1.73,57.0,athletics,0,0,0,29,114,1,2
21,763711985,Abdalelah Haroun,QAT,male,1997-01-01,1.85,80.0,athletics,0,0,0,19,152,1,2
22,924593601,Abdalla Targan,SUD,male,1996-09-28,1.77,65.0,athletics,0,0,0,20,170,1,2
23,578032534,Abdel Aziz Mehelba,EGY,male,1988-12-10,1.76,80.0,shooting,0,0,0,28,56,1,19
24,890222258,Abdelati El Guesse,MAR,male,1993-02-27,1.90,72.0,athletics,0,0,0,23,114,1,2
25,803161695,Abdelaziz Merzougui,ESP,male,1991-08-30,1.75,67.0,athletics,0,0,0,25,59,1,2
26,189931373,Abdelaziz Mohamed Ahmed,SUD,male,1994-10-12,1.81,72.0,aquatics,0,0,0,22,170,1,0
27,677622742,Abdelghani Demmou,ALG,male,1989-01-29,1.85,75.0,football,0,0,0,27,2,1,9
29,904808208,Abdelhakim Amokrane,ALG,male,1994-05-10,1.86,70.0,football,0,0,0,22,2,1,9
31,133974151,Abdelkadir Salhi,ALG,male,1993-03-19,1.85,79.0,football,0,0,0,23,2,1,9
32,189886442,Abdelkebir Ouaddar,MAR,male,2062-07-15,1.74,67.0,equestrian,0,0,0,-46,114,1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11505,47822121,Ziyu Zhang,AUS,female,1990-12-10,1.62,70.0,table tennis,0,0,0,26,10,0,20
11506,432416881,Zlatko Horvat,CRO,male,1984-09-25,1.79,86.0,handball,0,0,0,32,47,1,12
11507,446963221,Zoe Arancini,AUS,female,1991-07-14,1.70,70.0,aquatics,0,0,0,25,10,0,0
11508,499603226,Zoe Buckman,AUS,female,1988-12-21,1.68,50.0,athletics,0,0,0,28,10,0,2
11509,836633838,Zoe Lee,GBR,female,1985-12-15,1.76,70.0,rowing,0,1,0,31,67,0,16
11510,634140075,Zoe Stevenson,NZL,female,1991-06-19,1.83,74.0,rowing,0,0,0,25,138,0,16
11511,343671816,Zoe de Toledo,GBR,female,1987-07-17,1.72,58.0,rowing,0,1,0,29,67,0,16
11512,371106012,Zohar Shikler,ISR,female,1997-07-08,1.78,61.0,aquatics,0,0,0,19,90,0,0
11515,211176854,Zoi Kontogianni,GRE,female,1997-09-19,1.65,47.0,gymnastics,0,0,0,19,73,0,11
11516,875374176,Zokhid Kenjaev,UZB,male,1992-03-30,1.68,61.0,table tennis,0,0,0,24,192,1,20
11518,672182746,Zoltan Kovago,HUN,male,1979-04-10,2.04,132.0,athletics,0,0,0,37,82,1,2
11519,412827228,Zorana Arunovic,SRB,female,1986-11-22,1.68,90.0,shooting,0,0,0,30,166,0,19
11520,724419150,Zouhair Aouad,BRN,male,1989-04-07,1.75,69.0,athletics,0,0,0,27,27,1,2
11521,281890328,Zoulehia Abzetta Dabonne,CIV,female,1992-12-15,1.75,57.0,judo,0,0,0,24,39,0,14
11522,230998458,Zoya Ananchenko,KAZ,female,1996-09-05,1.65,67.0,canoe,0,0,0,20,97,0,5
11523,778588793,Zsanett Nemeth,HUN,female,1994-01-21,1.75,80.0,wrestling,0,0,0,22,82,0,26
11524,640253635,Zsofia Csonka,HUN,female,1983-09-12,1.64,89.0,shooting,0,0,0,33,82,0,19
11525,999437858,Zsofia Erdelyi,HUN,female,1987-12-10,1.64,53.0,athletics,0,0,0,29,82,0,2
11526,46916465,Zsofia Foldhazi,HUN,female,1993-06-09,1.70,54.0,modern pentathlon,0,0,0,23,82,0,15
11527,738530209,Zsofia Kovacs,HUN,female,1988-02-07,1.80,58.0,triathlon,0,0,0,28,82,0,23
11528,499425013,Zsofia Kovacs,HUN,female,2000-04-06,1.58,49.0,gymnastics,0,0,0,16,82,0,11
11529,862285226,Zsombor Berecz,HUN,male,1986-04-26,1.95,95.0,sailing,0,0,0,30,82,1,18
11530,739315046,Zsuzsanna Jakabos,HUN,female,1989-04-03,1.85,70.0,aquatics,0,0,0,27,82,0,0
11531,600541319,Zurabi Datunashvili,GEO,male,1991-06-18,1.83,75.0,wrestling,0,0,0,25,69,1,26
11532,801825063,Zurabi Iakobishvili,GEO,male,1992-02-04,1.71,68.0,wrestling,0,0,0,24,69,1,26
11533,265605954,Zurian Hechavarria,CUB,female,1995-08-10,1.64,58.0,athletics,0,0,0,21,48,0,2
11534,214461847,Zuzana Hejnova,CZE,female,1986-12-19,1.73,63.0,athletics,0,0,0,30,50,0,2
11535,88361042,di Xiao,CHN,male,1991-05-14,1.85,100.0,wrestling,0,0,0,25,38,1,26
11536,900065925,le Quoc Toan Tran,VIE,male,1989-04-05,1.60,56.0,weightlifting,0,0,0,27,195,1,25
11537,711404576,le Roux Hamman,RSA,male,1992-01-06,1.85,70.0,athletics,0,0,0,24,155,1,2

### Athletics has a wide variety of sizes, so we'll remove those to see how things turn out.

In [26]:
df = df[df.sport != 'athletics']

In [43]:
train, test = train_test_split(df, test_size=.3, random_state=123, stratify=df[['sport_enc']])

In [44]:
y_train = train[['sport_enc']]
y_test = test[['sport_enc']]

In [45]:
X_train = train[['sex_enc', 'height', 'weight', 'age', 'nationality_enc']]
X_test = test[['sex_enc', 'height', 'weight', 'age', 'nationality_enc']]

In [50]:
clf = DecisionTreeClassifier(criterion='entropy', max_depth=8, random_state=123).fit(X_train, y_train)

In [51]:
y_pred = clf.predict(X_train)
y_pred_proba = clf.predict_proba(X_train)

In [52]:
print('Accuracy of Decision Tree classifier on training set: {:.6f}'
     .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.315538

In [53]:
print('Accuracy of Decision Tree classifier on test set: {:.6f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.234819

### This is a simple decision tree with 27 different possible classifiers.  We'll try this again later with a random forest.